# Generated by Django 4.2.2 on 2023-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0003_jobapplication_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
