# Generated by Django 4.2.2 on 2023-06-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0006_jobapplication_remote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='attachments',
            field=models.ManyToManyField(to='job_hunt.attachment'),
        ),
    ]
