# Generated by Django 4.2.2 on 2023-06-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0007_attachment_jobapplication_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='job_hunt.jobapplication'),
        ),
    ]
