# Generated by Django 4.2.2 on 2023-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0008_remove_jobapplication_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
    ]
