# Generated by Django 4.2.2 on 2023-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='application_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
    ]
