# Generated by Django 4.2.2 on 2023-06-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0013_jobapplication_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='size',
            new_name='status',
        ),
    ]
