# Generated by Django 4.2.2 on 2023-06-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0014_rename_size_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_status',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('BACKLOG', 'Backlog'), ('DENIED', 'Denied'), ('INTERVIEW', 'Interview'), ('OFFER_RECIEVED', 'Offer recieved'), ('OFFER_REJECTED', 'Offer rejected'), ('OFFER_ACCEPTED', 'Offer accepted')], max_length=100, null=True),
        ),
    ]
