# Generated by Django 4.2.2 on 2023-06-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0018_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='careers_page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
