# Generated by Django 4.2.2 on 2023-06-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt', '0024_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
